# Generated by Django 3.1.4 on 2021-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='img_list',
            field=models.ImageField(default=123, upload_to='img/tours/', verbose_name='Мниатюра 370х302'),
            preserve_default=False,
        ),
    ]
