# Generated by Django 3.1.4 on 2021-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_tour_img_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default=123, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
