# Generated by Django 3.1.4 on 2021-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(default=123, verbose_name='Описание на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ko',
            field=models.TextField(default=123, verbose_name='Описание на корейском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(default=123, verbose_name='Описание на русском'),
            preserve_default=False,
        ),
    ]
