# Generated by Django 3.1.4 on 2021-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210116_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=123, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
