# Generated by Django 3.1.4 on 2021-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.BigIntegerField(verbose_name='Цена'),
        ),
    ]
