# Generated by Django 3.1.4 on 2021-01-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210116_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='img_detail',
            field=models.ImageField(default=123, upload_to='img/tours/', verbose_name='Изображение (870х400)'),
            preserve_default=False,
        ),
    ]
