# Generated by Django 3.1.4 on 2021-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_order_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_uz',
            field=models.TextField(default=123, verbose_name='Описание на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='name_uz',
            field=models.CharField(default=123, max_length=200, verbose_name='Название на узбекском'),
            preserve_default=False,
        ),
    ]
